### ISSUE TITLE
Updating imgix-rb dependency to v4?

### ISSUE THREAD

**Issue by causztic** [imgix/imgix-rails#102]
**Question**
Hi, are there plans to update the imgix-rb dependency to v4? That uses an updated version of the `purge` command, and I couldn't get the v3 purge functionality working.

**Comment by ericdeansanchez** [comment]
Hey 👋 thanks for opening an issue! Yes, there are plans to update the imgix-rb dependency. I will give you an update once the update is deployed :)

**Comment by causztic** [comment]
thank you!
