### ISSUE TITLE
Would be nice to see an example working with Refile

### ISSUE THREAD

**Issue by andrewhavens** [imgix/imgix-rails#19]
I am currently using Refile to handle image uploads and resizing in my app. However, I'm moving to using imgix. It would be nice to see an example of how to easily migrate to using imgix without much modification on my part.

**Comment by paulstraw** [comment]
Hey @andrewhavens, great question. I've actually had to do this before, and it's fairly straightforward. Essentially what you'll be doing is using Refile only for uploading, pointing an imgix source to wherever your refile images live, then passing the uploaded file URLs to imgix. Here's a quick example using S3 that I snagged from a past project (hopefully enough to get you headed in the right direction), and I'll make sure to get a full guide into the readme early next week! 

``` ruby
module ImgixRefileHelper
  def ix_rf_image_url(obj, key, **opts)
    path = s3_path(obj, key)
    path ? ix_image_url(path, opts) : ''
  end

  def ix_rf_image_tag(obj, key, **opts)
    path = s3_path(obj, key)
    path ? ix_image_tag(path, opts) : ''
  end

private
  def s3_path(obj, key)
    refile_id = obj["#{key}_id"]
    s3_prefix = obj.send(key).try(:backend).instance_variable_get(:@prefix)

    s3_prefix ? "#{s3_prefix}/#{refile_id}" : nil
  end
end
```

``` html
<%= ix_rf_image_tag(@blog_post, :hero_photo, {auto: 'format', fit: 'crop', w: 500})
```

**Comment by andrewhavens** [comment]
That helps, thanks!

**Comment by kellysutton** [comment]
Implemented in the README. Closing.
