### ISSUE TITLE
When given a fixed `w:` input value, generate appropriate `w` values for known DPRs

### ISSUE THREAD

**Issue by kellysutton** [imgix/imgix-rails#25]
To better hit the `1x`, `2x`, etc. case while still strictly adhering to generating only `w`-style `srcset` rules, imgix-rails should be smarter about how it generates `srcset` rules.

This will come into play for things like fixed-width avatars that only need to be resolution-switched across different DPRs.

Developers should be able to write:

```erb
<%= ix_image_tag('/avatar.jpg', { w: 40, h: 40, sizes: "40px", max_width: 120 } %>
```

And have imgix-rails generate the following: 

```erb
<img srcset="https://source.imgix.net/avatar.jpg?w=40&amp;h=40 40w,
             https://source.imgix.net/avatar.jpg?w=80&amp;h=80 80w,
             https://source.imgix.net/avatar.jpg?w=120&amp;h=120 120w"
     sizes="40px"
     src="https://source.imgix.net/avatar.jpg?w=40&amp;h=40 40w"
/>
```

See the conversation here for some context: https://imgix-community.slack.com/archives/general/p1464697975000282

**Comment by klesht** [comment]
This kind of flexibility would be most appreciated! Expanding on the above, would love to have full control over the array of sizes that `imgix-rails` generates.  Whereby, something like:

`<%= ix_image_tag('/avatar.jpg', { w: ['40', '80', '160'], sizes: "(min-width: 1500px) 25vw, (min-width: 850px) 33vw, (min-width: 550px) 50vw, 100vw" } %>`

Might generate:
```
<img srcset="https://source.imgix.net/avatar.jpg?w=40 40w,
             https://source.imgix.net/avatar.jpg?w=80 80w,
             https://source.imgix.net/avatar.jpg?w=160 160w"
     sizes="(min-width: 1500px) 25vw, (min-width: 850px) 33vw, (min-width: 550px) 50vw, 100vw"
     src="https://source.imgix.net/avatar.jpg?w=40&amp 40w"
/>
```
