### ISSUE TITLE
`widths` option is rendered in HTML

### ISSUE THREAD

**Issue by kellysutton** [imgix/imgix-rails#27]
When specifying a `:widths` option to `#ix_image_tag`, that option gets carried through and rendered as an attribute in the resulting HTML. This results in something that looks like the following:

```html
<img src="..." widths="250 500 750" />
```

**Expected Result:**

The `widths` attribute does not appear in the rendered HTML when specified as an option in `#ix_image_tag`.

**Comment by paulstraw** [comment]
Good catch, I'll get this fixed up. Thanks Kelly!

**Comment by paulstraw** [comment]
Released as 2.1.1, thanks again @kellysutton.
