### ISSUE TITLE
Rails gem version as a param in helper method URLs is rendered in resulting image's alt-tag

### ISSUE THREAD

**Issue by amdixon** [imgix/imgix-rails#30]
When using any of the IMGIX Rails gem helper methods (ix_image_tag, ix_picture_tag, ix_image_url) the resulting IMGIX URL(s) include the rails gem name and version as the first param. This subsequently is rendered in the image's alt-tag (Rails by default renders the image file name if you don't explicitly pass an alt: option in image_tag).

Example URL: `example.imgix.net/bucket/file-name.jpg?ixlib=rails-2.1.1&w=300&h=300`

Without the ixlib=rails param the alt-tag looks like: `alt="file name"`
With the ixlib=rails param the alt-tag looks like: `alt="file name.jpg?ixlib=rails 2.1"`

Would it be possible to remove the ixlib from the URL params, or pass it along in some other way so it doesn't interfere with Rails native alt-tagging abilities?

Ruby version: 2.3.1p112
Rails version: 5.0.0
IMGIX gem version: 2.1.1

**Comment by paulstraw** [comment]
Hey @amdixon, you can disable generating the `ixlib` param by adding `include_library_param: false` to your config hash. That should do the trick, but feel free to reopen this issue if you have more questions.

**Comment by nguyenj** [comment]
This `include_library_param` param is lacking in the docs-would be helpful to provide all the params that are available.
