### ISSUE TITLE
Update config/application.rb instructions for Rails 5

### ISSUE THREAD

**Issue by kellysutton** [imgix/imgix-rails#31]
There's no more concept of a config block parameter in the `config/application.rb` file, meaning the instructions in the README aren't applicable.

**Comment by paulstraw** [comment]
Did you mean to close this @kellysutton?

**Comment by kellysutton** [comment]
Yep. Jumped the gun a bit. Wasn't looking in the `config/environments/*` files, which do have the config blocks.
