### ISSUE TITLE
Imgix for background images (rails)

### ISSUE THREAD

**Issue by robbiehudson** [imgix/imgix-rails#33]
Hey,

The guys in Imgix support told me to come here so hoping someone might be able to help me with a rails questions. What's the easiest way to serve up CSS background images using Imgix? Or do I have to wait for this to be implemented: https://github.com/imgix/imgix-rails/issues/10

Thanks!

Rob

**Comment by paulstraw** [comment]
Hey @robbiehudson, I just released this as [2.1.3](https://github.com/imgix/imgix-rails/releases/tag/2.1.3). Here are some docs on how to use it: https://github.com/imgix/imgix-rails#usage-in-sprockets. Let me know if you run into any issues!
