### ISSUE TITLE
Broken for Ruby < 2.1 due to required keyword arguments

### ISSUE THREAD

**Issue by ccamrobertson** [imgix/imgix-rails#35]
The required keyword arguments in ix_picture_tag in view_helper.rb aren't supported in Ruby < 2.1. 

It would be helpful for 3.2 and 4.2 apps running on older Rubies to swap these for hashes, although some additional work might be done if you want to throw errors in the case of a missing parameter here.

**Comment by paulstraw** [comment]
Hmm. Ruby < 2.1 has been EOL'd, and 2.1.10 is nearing EOL. I'd accept a PR for this that uses a hash there, and checks for the necessary keys. Would you be interested in writing that, @ccamrobertson?

**Comment by ccamrobertson** [comment]
@paulstraw I started work on one; while it solved the hash issue another issue with loading the config variables cropped up.

We've got a time critical project I need to focus on first, so I will stick around on 1.1.0 until I have the time to dig in.
