### ISSUE TITLE
Option to designate format in the request

### ISSUE THREAD

**Issue by etcook** [imgix/imgix-rails#37]
According to the imgix API documentation, you can get the exif data by utilizing the fm modifier. Unfortunately, that doesn't seem to be supported within imgix-rails. Adding the fm option would be helpful.

**Comment by abrambailey** [comment]
Here's what I've done to use `fm` to grab webp-format images:

`ix_image_url(self.image.key, IMAGE_SIZES_IX[size.to_sym]) + '&fm=webp'`

In mimi_types.rb:

`IMAGE_SIZES_IX = {xl: { w: 1000, h: 1000 }, large: { w: 500, h: 500 }`

**Comment by sherwinski** [comment]
To add to what @abrambailey said, you can also pass in `fm` directly as a parameter:

```rb
<%= ix_image_url('unsplash/bridge.jpg', {fm:'json'}) %>
```

Using the `ix_image_url` function will generate a URL whose response body would contain the exif data. This would be preferred over using `ix_image_tag` which would wrap the same URL in an `<img>` tag.

I'm going to close this issue as it is fairly old, but feel free to comment back if any further questions arise.
