### ISSUE TITLE
`widths` option is appended to the IMGIX url

### ISSUE THREAD

**Issue by Tailzip** [imgix/imgix-rails#43]
Hi,

When specifying a `widths` option, it gets appended to the generated IMGIX url like so:
```
...?auto=format&fit=max&h=120&q=60&w=280&widths=%5B280%2C%20335%2C%20374%2C%20560%2C%20670%2C%20748%2C%20768%2C%201024%2C%201200%2C%201400%2C%201536%2C%201600%2C%201800%2C%202000%2C%202048%2C%202200%2C%202400%2C%202800%2C%203200%2C%203600%2C%204000%2C%204400%5D
```

And it's _polluting_ the HTML: 

![screenshot](https://d2ppvlu71ri8gs.cloudfront.net/items/0y0X1k2v1i032V21411Z/Screen%20Shot%202017-05-19%20at%2012.41.35.png?v=99a89271)

Any chance it can be removed?

Thanks!

**Comment by cherifzouein** [comment]
+1!!!

**Comment by lucianopanaro** [comment]
+1

**Comment by emaraschio** [comment]
+1

**Comment by jfyzhao** [comment]
Still seeing this happen with 2.1.4 @jayeb @gitmiggi

**Comment by jfyzhao** [comment]
It is causing the w option to not work at all for me. Don't know if anyone else is seeing this. Don't think it has anything to do with how I'm using the ix_image_tag, esp. since h and other options appear to work fine.

**Comment by jayeb** [comment]
@jfyzhao I thought I saw a couple of messages come through last night about continuing issues with this, but they're gone now. Is everything good?

**Comment by jfyzhao** [comment]
@jayeb I still see an extremely large srcset generated by default but after looking at the docs more closely I think that is the intended behavior?

**Comment by jayeb** [comment]
@jfyzhao Yup, that's exactly the intended behavior. If you have any further questions or issues I'm happy to chat either in a separate ticket or in our community Slack, but I'm gonna lock conversation on this ticket since there are a fairly high number of folks subscribed at this point who might not appreciate being spammed by a longer conversation between you and I 😅 .
