### ISSUE TITLE
Multiple secure_url_tokens when using multiple sources

### ISSUE THREAD

**Issue by jfyzhao** [imgix/imgix-rails#46]
I'm a little confused about some of the usage around having multiple sources.

First, how do I designate multiple secure_url_tokens when I have multiple sources. I see in the documentation that Source can be an array and so can hostnames_to_replace, but I don't see anything about secure_url_tokens. Looking at my Imgix sources, looks like the secure_url_token is different for each source.

Secondly, how do I specify on each individual ix_image_tag which source, hostname, and secure_url_token it should be using?

Thanks!

**Comment by andrewhood125** [comment]
So I wanted to use multiple sources and be able to specify each one from the helper. We have some assets in s3 and some in our repo. 

Long story short, the multiple hosts are for sharding. imgix-rails doesn't have any hand in it, it comes from the underlying imgix gem. PR is here: https://github.com/imgix/imgix-rb/pull/3/files and there are some docs in the imgix-rb repo about the motivation behind sharding.

**Comment by piya23300** [comment]
I'm confused too.

How to use it?

```ruby
Rails.application.configure do
  config.imgix = {
    sources: {
      "assets_foobarbaz.imgix.net"  => "foobarbaz",
      "assets_nil.imgix.net" => nil,   # Will generate unsigned URLs
    },
    default_source: "default_source.imgix.net"
  }
end
```

```ruby
include Imgix::Rails::UrlHelper

puts ix_image_url('/users/1/avatar.png', { w: 400, h: 300 })
# => https://assets_nil.imgix.net/users/1/avatar.png?w=400&h=300
```

I expet to use below but it's not work T.T
```
puts ix_image_url('foobarbaz', '/users/1/avatar.png', { w: 400, h: 300 })
# I expect
# => https://assets_foobarbaz.imgix.net/users/1/avatar.png?w=400&h=300
# I show error
# =>  Unknown source 'foobarbaz'
```

Can someone help me?

**Comment by sherwinski** [comment]
Closing as this issue is quite old. If anyone still has questions about multi-source support, please feel free to comment here or open a new issue altogether.
