### ISSUE TITLE
Support Multiple Sources

### ISSUE THREAD

**Issue by benhutton** [imgix/imgix-rails#48]
We would like to serve images from multiple s3 buckets and our website simultaneously. Imgix allows us to configure multiple sources. It would be useful if this gem would make those multiple sources easy to use!

Ideally, I'd get a hash mapping hostnames to rewrite to the source to rewrite them to. Maybe something like this:

```
Rails.application.configure do
  config.imgix = {
    sources: {
      'assets.myapp.com' => 'myapp.imgix.net',
      'www.myapp.com' => 'myapp1.imgix.net',
      'assets2.myapp.com' => 'myapp2.imgix.net'
    }
  }
end
```

I'd be happy to work on this, if it is a feature that you would merge.

**Comment by octave** [comment]
Would be nice!

**Comment by sherwinski** [comment]
Completed in #56

**Comment by benhutton** [comment]
@sherwinski I think this got closed incorrectly. #56 was about a different issue, as https://github.com/imgix/imgix-rails/pull/56#issuecomment-413381852 explains

**Comment by benhutton** [comment]
oh, it got completed in https://github.com/imgix/imgix-rails/pull/61
