### ISSUE TITLE
Switching between dev (local filesystem) and production (aws s3)

### ISSUE THREAD

**Issue by KillerCodeMonkey** [imgix/imgix-rails#64]
Hey guys,

you removed the `hostnames_to_replace` config so i need to switch to relative paths of my images.
I am using it with Carrierwave and AWS S3 in production and local file system for local development.
What is you approach to switch between those things with imgix?

Greets and thanks :)

**Comment by jayeb** [comment]
Hi @KillerCodeMonkey,

We decided to remove the `hostnames_to_replace` functionality as part of an ongoing effort to hone and focus the functionality of our client libraries to unify them and focus on the most important features. We determined that this kind of hostname replacement was a rare enough use case and was relatively trivial for an end-developer to implement directly that it should not be supported as a first-class feature of this library.

You should be able to replicate the old `hostnames_to_replace` functionality without too much fuss by doing some string manipulation on your URLs before you pass them into any imgix helper functions. Here's how we were doing this [previously](https://github.com/imgix/imgix-rails/blob/v2.1.4/lib/imgix/rails/url_helper.rb#L27-L38):

```rb
def replace_hostname(source)
  new_source = source.dup

  # Replace any hostnames configured to trim things down just to their paths.
  # We use split to remove the protocol in the process.
  hostnames_to_remove.each do |hostname|
    splits = source.split(hostname)
    new_source = splits.last if splits.size > 1
  end

  new_source
end
```

Hope this helps. I'm gonna close this ticket, but please re-open if you have any issues or further questions.

**Comment by KillerCodeMonkey** [comment]
Hey there. Thanks for the response. To avoid an additional env variable
that Stores the replace Hostname. I added a View helper, that switchs
between image.path (rails.env.production) and .url (Dev).

On local Dev i Set the imgix source to http://localhost:3000

So when i use imgix viewhelpers i pass the path through my `path_per_env`
helper.

Jason Eberle <notifications@github.com> schrieb am Mi., 24. Okt. 2018,
21:47:
