### ISSUE TITLE
SemVer? Changelog?

### ISSUE THREAD

**Issue by andrewhood125** [imgix/imgix-rails#65]
Hi Imgix!

Saw that you recently released a new major version. Does this repo follow semver?

Do you have a changelog? What broke backwards compatibility in the new release?

It wasn't obvious from this: https://github.com/imgix/imgix-rails/compare/v2.1.4...v3.0.0

**Comment by jayeb** [comment]
Sorry folks, this is on me. We rolled a new version of the library about a month ago but I never actually created a Release with notes about the changes. I'll take care of this today.

**Comment by jayeb** [comment]
The published version and release notes are here: https://github.com/imgix/imgix-rails/releases/tag/v3.0.0. Sorry about the delay!

**Comment by KillerCodeMonkey** [comment]
Thanks! :)

Jason Eberle <notifications@github.com> schrieb am Mi., 24. Okt. 2018,
21:36:
