### ISSUE TITLE
extra srcset link generated causes issue on non-retina displays

### ISSUE THREAD

**Issue by jholmes12** [imgix/imgix-rails#68]
After adding imgix-rails, we noticed that an extra srcset was being included at the very end of the generated srcset links causing non-retina displays to not handle the image properly. This additional srcset link does not include a fixed size attribute like all the others.

When the browser is viewed on a retina display, the correct srcset is used and all is well- but when the browser is loaded on a **non-retina display** this extra srcset is used by default and does not render as intended on the page.

Does anyone know the purpose of this extra srcset link that is generated after all the ones with defined sizes?

Here is the code from the imgix-rails gem that generates the srcset links. The extra link that is causing issues has been underlined.

![screen shot 2018-11-19 at 2 43 19 pm](https://user-images.githubusercontent.com/7647506/48734873-6569df00-ec0c-11e8-9786-7986ee472ac8.png)

Here you can see the end of the srcset links that are generated, and the link pointed to by the arrow does not have a defined size like the others.

![screen shot 2018-11-19 at 2 39 05 pm](https://user-images.githubusercontent.com/7647506/48735046-dc06dc80-ec0c-11e8-896b-8ff34b19b260.png)

Below are two profile cards, where the one with the image not displaying correctly is when the browser was on a non-retina display.
![screen shot 2018-11-19 at 2 45 52 pm](https://user-images.githubusercontent.com/7647506/48735180-43bd2780-ec0d-11e8-91a8-1c3b6793707b.png)

Here the image shows correctly when viewed on a retina display.
<img width="308" alt="screen shot 2018-11-19 at 2 46 21 pm" src="https://user-images.githubusercontent.com/7647506/48735205-56376100-ec0d-11e8-912e-ca2d6a6ba3be.png">

Locally, commenting out the line of code that generates the extra srcset resolves this issue and all images work perfectly on both retina and non-retina displays.  If this additional srcset link is not needed and causing issues, could it be removed from the gem?  Also I noticed that if you check out the images on imgix's actual website, they don't include this extra srcset.

Thanks so much for your help!

**Comment by jayeb** [comment]
Hey @jholmes12, thanks for catching this. Your instincts are correct, this widthless source shouldn't be there. I've made a fix in #69. Would you mind giving it a quick review before I merge & release?
