### ISSUE TITLE
Support latest version of imgix-rb

### ISSUE THREAD

**Issue by dwightwatson** [imgix/imgix-rails#75]
There is a [runtime dependency for `~ 1.1`](https://github.com/imgix/imgix-rails/blob/master/imgix-rails.gemspec#L30) despite the latest version being `3.1.1`. 

Would be great if this constraint was updated so we can use the latest version under the hood.

**Comment by sherwinski** [comment]
👍 Definitely agree, there will be also be some significant changes coming in the near future which will rely on the newer version of imgix-rb
