### ISSUE TITLE
How to use inside a model?

### ISSUE THREAD

**Issue by robypez** [imgix/imgix-rails#77]
Hello, I have to parse an html with some img tag in my model and I need to save in a callback the responsive images. 
How can I call these helpers in my model?

**Comment by sherwinski** [comment]
Hi @robypez apologies for the late response. Could you possibly provide more details as to what you're looking for? It would help me considerably in trying to provide a possible example. Thanks

**Comment by robypez** [comment]
Inside a model

`ix_image_tag('/unsplash/hotairballoon.jpg', url_params: { w: 300, h: 500, fit: 'crop', crop: 'right'}, tag_options: { alt: 'A hot air balloon on a sunny day'  `

Method not found. But this works. I need to use ix_img_tag with nokogiri in my content model

```
include Imgix::Rails::UrlHelper

puts ix_image_url('/users/1/avatar.png', { w: 400, h: 300 })
# => https://assets.imgix.net/users/1/avatar.png?w=400&h=300
```

**Comment by courtsimas** [comment]
The documentation has no info on using these helpers or similar methods outside of the context of views. (for instance, in controllers, or in custom presenters). That would be nice to know...

**Comment by karimmorta** [comment]
It could be clearer in the docs thought as this will be often used in an API context :)

**Comment by robypez** [comment]
In the model I'm using Imgix Ruby now

**Comment by ericdeansanchez** [comment]
Hello :wave: @karimmorta @robypez I'd love to help here. It seems what's being asked here is better or more descriptive documentation related to use inside of models.

My question is, what kind of documentation would help in this situation? Is there a particular feature that seems to be missing or missing documentation? Is there a common task here that could be described and/or documented better?

I'm fairly new here at imgix and I'm just trying to build up a little context.

I appreciate and look forward to you feedback! :)

**Comment by courtsimas** [comment]
Can’t people just extend the imgix module inside the model and use the helper just like in a view? That’s what we do. Takes 2 seconds to do.

**Comment by karimmorta** [comment]
@courtsimas That's actually what I did and it's indeed super simple. 
Just feels a bit awkard to include url_helpers in the model but I guess it's fine, nothing wrong with that.
The better solution is probably to use the ruby client as suggested by @robypez 

Hey @ericdeansanchez, maybe I was reading the doc too fast, but I think the part about including the helpers in the model ("...This is useful for things such as including imgix URLs in JSON output from a serializer class...") should have a subtitle above it (with keywords like model, API, or something like that). I was having the impression that I couldn't use this outside of html/erb views.

👋

**Comment by ericdeansanchez** [comment]
@karimmorta Great! I am glad you've found a solution.

> a subtitle above it (with keywords like model, API, or something like that).  I was having the impression that I couldn't use this outside of html/erb views.

I think this could be a great addition; I will collect the context of this conversation into improved documentation + an example.

@courtsimas
>Can’t people just extend the imgix module inside the model and use the helper just like in a view?

Yes! :)
