### ISSUE TITLE
`min_width` and `max_width` are rendered to HTML tag

### ISSUE THREAD

**Issue by gasi** [imgix/imgix-rails#82]
![image](https://user-images.githubusercontent.com/49583/69100832-ecfe4f80-0a12-11ea-91db-707ca77f3a5f.png)

`min_width` and `max_width` should be stripped before generating the HTML. Better yet: Could we move `min_width` and `max_width` out of `tag_options` into some form of Imgix `options`?

**Comment by sherwinski** [comment]
Hey @gasi I certainly can remove them from the generated HTML! I'm currently refactoring a lot of our srcset generation functionality so I will have to see how moving srcset capabilities out of `tag_options` will look for this gem.
